name: duckdb demo build
on:
  pull_request_review:
    types: [submitted]

jobs:
  mimic-iv-duckdb:
    # only run if PR is approved
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-20.04

    steps:
      - name: Check out repository code
        uses: actions/checkout@v3

      - name: Download duckdb CLI
        run: |
          wget https://github.com/duckdb/duckdb/releases/download/v0.6.1/duckdb_cli-linux-amd64.zip
          unzip duckdb_cli-linux-amd64.zip
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          mkdir -p "$HOME/.local/bin"
          mv duckdb "$HOME/.local/bin/duckdb"

      - name: Download demo data
        uses: ./.github/actions/download-demo

      - name: Load icu/hosp data into duckdb
        run: |
          echo "Running duckdb build."
          cd ${BUILDCODE_PATH}
          ./import_duckdb.sh ./

          echo `md5sum mimic4.db`

        env:
          BUILDCODE_PATH: mimic-iv/buildmimic/duckdb
